variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: clone

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  image: gradle:alpine
  script: bash ./gradlew --build-cache assemble
  only:
    refs:
      - branches

test:
  stage: test
  image: gradle:alpine
  script: bash ./gradlew check
  only:
    refs:
      - branches

deploy-on-test-server:
  stage: deploy
  image: gradle:alpine
  script:
    - sudo dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
      - develop

build_production:
  stage: build
  image: gradle:alpine
  script: bash ./gradlew --build-cache assemble
  only:
    - master

test_production:
  stage: test
  image: gradle:alpine
  script: bash ./gradlew check
  only:
    - master

deploy-on-production-server:
  stage: deploy
  image: gradle:alpine
  script:
    - sudo --provider=heroku --app=$HEROKU_APP_NAME_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master